name: autocommit_avoid_github_limition
on:
  schedule:
    - cron: "0 0 21 * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@master
        
      - name: append random char
        run: echo FOO=foobar--$(date +%s) >> random.txt
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: auto commit
      
